image: "golang:alpine"
script:
  - DOCKER_CLI_VERSION="17.06.2-ce"
  - DOWNLOAD_URL="https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_CLI_VERSION.tgz"
  - apk --update add curl \
    && mkdir -p /tmp/download \
    && curl -L $DOWNLOAD_URL | tar -xz -C /tmp/download \
    && mv /tmp/download/docker/docker /usr/local/bin/ \
    && rm -rf /tmp/download \
    && apk del curl
    && rm -rf /var/cache/apk/*
  - apk add git alpine-sdk
  - go get github.com/tidwall/buntdb
  - go get github.com/benchlab-io/go-bench
