image: "golang:alpine"
script:
  - echo hello1
  - apk add git alpine-sdk
  - go get github.com/tidwall/buntdb
  - go get github.com/benchlab-io/go-bench
  - cd /go/src/github.com/tidwall/buntdb
  - go test --bench=. | go-bench
